[2025-03-16T21:56:59.610+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-16T21:56:59.649+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_ingestion_gcs_dag.create_stations_external_table manual__2025-03-16T21:51:17.045850+00:00 [queued]>
[2025-03-16T21:56:59.686+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_ingestion_gcs_dag.create_stations_external_table manual__2025-03-16T21:51:17.045850+00:00 [queued]>
[2025-03-16T21:56:59.687+0000] {taskinstance.py:2867} INFO - Starting attempt 2 of 2
[2025-03-16T21:56:59.708+0000] {taskinstance.py:2890} INFO - Executing <Task(BigQueryCreateExternalTableOperator): create_stations_external_table> on 2025-03-16 21:51:17.045850+00:00
[2025-03-16T21:56:59.718+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=839) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-16T21:56:59.721+0000] {standard_task_runner.py:72} INFO - Started process 841 to run task
[2025-03-16T21:56:59.721+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'create_stations_external_table', 'manual__2025-03-16T21:51:17.045850+00:00', '--job-id', '706', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmp559dm_n2']
[2025-03-16T21:56:59.723+0000] {standard_task_runner.py:105} INFO - Job 706: Subtask create_stations_external_table
[2025-03-16T21:56:59.800+0000] {task_command.py:467} INFO - Running <TaskInstance: data_ingestion_gcs_dag.create_stations_external_table manual__2025-03-16T21:51:17.045850+00:00 [running]> on host 5c7a1daace86
[2025-03-16T21:56:59.980+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_ingestion_gcs_dag' AIRFLOW_CTX_TASK_ID='create_stations_external_table' AIRFLOW_CTX_EXECUTION_DATE='2025-03-16T21:51:17.045850+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-16T21:51:17.045850+00:00'
[2025-03-16T21:56:59.983+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-16T21:56:59.984+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-16T21:56:59.985+0000] {logging_mixin.py:190} INFO - Current task name:create_stations_external_table state:running start_date:2025-03-16 21:56:59.650914+00:00
[2025-03-16T21:56:59.986+0000] {logging_mixin.py:190} INFO - Dag name:data_ingestion_gcs_dag and current dag run status:running
[2025-03-16T21:56:59.987+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-16T21:56:59.989+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2025-03-16T21:56:59.991+0000] {connection.py:277} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2025-03-16T21:56:59.993+0000] {base.py:84} INFO - Retrieving connection 'google_cloud_default'
[2025-03-16T21:57:01.297+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 1656, in execute
    self._table = bq_hook.create_empty_table(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/common/hooks/base_google.py", line 553, in inner_wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 457, in create_empty_table
    return self.get_client(project_id=project_id, location=location).create_table(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/client.py", line 797, in create_table
    api_response = self._call_api(
                   ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/client.py", line 831, in _call_api
    return call()
           ^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 293, in retry_wrapped_func
    return retry_target(
           ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 153, in retry_target
    _retry_error_helper(
  File "/home/airflow/.local/lib/python3.12/site-packages/google/api_core/retry/retry_base.py", line 212, in _retry_error_helper
    raise final_exc from source_exc
  File "/home/airflow/.local/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 144, in retry_target
    result = target()
             ^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/_http/__init__.py", line 494, in api_request
    raise exceptions.from_http_response(response)
google.api_core.exceptions.BadRequest: 400 POST https://bigquery.googleapis.com/bigquery/v2/projects/kestra-sandbox-451604/datasets/Indego_project/tables?prettyPrint=false: Error while reading table: indego_stations, error message: Parquet file contains invalid empty field name in schema: required group field_id=-1 schema {
  optional int64 field_id=-1 Station_ID;
  optional binary field_id=-1 Station_Name (String);
  optional binary field_id=-1 Day of Go_live_date (String);
  optional binary field_id=-1 Status (String);
  optional int32 field_id=-1  (Null);
  optional int32 field_id=-1  (Null);
  optional int32 field_id=-1  (Null);
  optional int32 field_id=-1  (Null);
  optional int32 field_id=-1  (Null);
  optional int32 field_id=-1  (Null);
  optional int32 field_id=-1  (Null);
  optional int32 field_id=-1  (Null);
  optional int32 field_id=-1  (Null);
}
 File: gs://kestra-de-zoomcamp-bucket-kelly/raw/indego_stations.parquet
[2025-03-16T21:57:01.312+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-03-16T21:57:01.313+0000] {logging_mixin.py:190} INFO - Task start:2025-03-16 21:56:59.650914+00:00 end:2025-03-16 21:57:01.311717+00:00 duration:1.660803
[2025-03-16T21:57:01.314+0000] {logging_mixin.py:190} INFO - Task:<Task(BigQueryCreateExternalTableOperator): create_stations_external_table> dag:<DAG: data_ingestion_gcs_dag> dagrun:<DagRun data_ingestion_gcs_dag @ 2025-03-16 21:51:17.045850+00:00: manual__2025-03-16T21:51:17.045850+00:00, state:running, queued_at: 2025-03-16 21:51:17.198952+00:00. externally triggered: True>
[2025-03-16T21:57:01.314+0000] {logging_mixin.py:190} INFO - Failure caused by 400 POST https://bigquery.googleapis.com/bigquery/v2/projects/kestra-sandbox-451604/datasets/Indego_project/tables?prettyPrint=false: Error while reading table: indego_stations, error message: Parquet file contains invalid empty field name in schema: required group field_id=-1 schema {
  optional int64 field_id=-1 Station_ID;
  optional binary field_id=-1 Station_Name (String);
  optional binary field_id=-1 Day of Go_live_date (String);
  optional binary field_id=-1 Status (String);
  optional int32 field_id=-1  (Null);
  optional int32 field_id=-1  (Null);
  optional int32 field_id=-1  (Null);
  optional int32 field_id=-1  (Null);
  optional int32 field_id=-1  (Null);
  optional int32 field_id=-1  (Null);
  optional int32 field_id=-1  (Null);
  optional int32 field_id=-1  (Null);
  optional int32 field_id=-1  (Null);
}
 File: gs://kestra-de-zoomcamp-bucket-kelly/raw/indego_stations.parquet
[2025-03-16T21:57:01.315+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=data_ingestion_gcs_dag, task_id=create_stations_external_table, run_id=manual__2025-03-16T21:51:17.045850+00:00, execution_date=20250316T215117, start_date=20250316T215659, end_date=20250316T215701
[2025-03-16T21:57:01.349+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-16T21:57:01.350+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 706 for task create_stations_external_table (400 POST https://bigquery.googleapis.com/bigquery/v2/projects/kestra-sandbox-451604/datasets/Indego_project/tables?prettyPrint=false: Error while reading table: indego_stations, error message: Parquet file contains invalid empty field name in schema: required group field_id=-1 schema {
  optional int64 field_id=-1 Station_ID;
  optional binary field_id=-1 Station_Name (String);
  optional binary field_id=-1 Day of Go_live_date (String);
  optional binary field_id=-1 Status (String);
  optional int32 field_id=-1  (Null);
  optional int32 field_id=-1  (Null);
  optional int32 field_id=-1  (Null);
  optional int32 field_id=-1  (Null);
  optional int32 field_id=-1  (Null);
  optional int32 field_id=-1  (Null);
  optional int32 field_id=-1  (Null);
  optional int32 field_id=-1  (Null);
  optional int32 field_id=-1  (Null);
}
 File: gs://kestra-de-zoomcamp-bucket-kelly/raw/indego_stations.parquet; 841)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 1656, in execute
    self._table = bq_hook.create_empty_table(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/common/hooks/base_google.py", line 553, in inner_wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 457, in create_empty_table
    return self.get_client(project_id=project_id, location=location).create_table(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/client.py", line 797, in create_table
    api_response = self._call_api(
                   ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/client.py", line 831, in _call_api
    return call()
           ^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 293, in retry_wrapped_func
    return retry_target(
           ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 153, in retry_target
    _retry_error_helper(
  File "/home/airflow/.local/lib/python3.12/site-packages/google/api_core/retry/retry_base.py", line 212, in _retry_error_helper
    raise final_exc from source_exc
  File "/home/airflow/.local/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 144, in retry_target
    result = target()
             ^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/_http/__init__.py", line 494, in api_request
    raise exceptions.from_http_response(response)
google.api_core.exceptions.BadRequest: 400 POST https://bigquery.googleapis.com/bigquery/v2/projects/kestra-sandbox-451604/datasets/Indego_project/tables?prettyPrint=false: Error while reading table: indego_stations, error message: Parquet file contains invalid empty field name in schema: required group field_id=-1 schema {
  optional int64 field_id=-1 Station_ID;
  optional binary field_id=-1 Station_Name (String);
  optional binary field_id=-1 Day of Go_live_date (String);
  optional binary field_id=-1 Status (String);
  optional int32 field_id=-1  (Null);
  optional int32 field_id=-1  (Null);
  optional int32 field_id=-1  (Null);
  optional int32 field_id=-1  (Null);
  optional int32 field_id=-1  (Null);
  optional int32 field_id=-1  (Null);
  optional int32 field_id=-1  (Null);
  optional int32 field_id=-1  (Null);
  optional int32 field_id=-1  (Null);
}
 File: gs://kestra-de-zoomcamp-bucket-kelly/raw/indego_stations.parquet
[2025-03-16T21:57:01.386+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-16T21:57:01.418+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-16T21:57:01.422+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
