[2025-03-16T19:58:21.696+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-16T19:58:22.091+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_ingestion_bigquery_dag.merge_all_trips scheduled__2025-03-15T00:00:00+00:00 [queued]>
[2025-03-16T19:58:22.195+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_ingestion_bigquery_dag.merge_all_trips scheduled__2025-03-15T00:00:00+00:00 [queued]>
[2025-03-16T19:58:22.196+0000] {taskinstance.py:2867} INFO - Starting attempt 2 of 3
[2025-03-16T19:58:22.398+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): merge_all_trips> on 2025-03-15 00:00:00+00:00
[2025-03-16T19:58:22.517+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1247) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-16T19:58:22.520+0000] {standard_task_runner.py:72} INFO - Started process 1256 to run task
[2025-03-16T19:58:22.545+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_bigquery_dag', 'merge_all_trips', 'scheduled__2025-03-15T00:00:00+00:00', '--job-id', '46', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs.py', '--cfg-path', '/tmp/tmpczran7zo']
[2025-03-16T19:58:22.551+0000] {standard_task_runner.py:105} INFO - Job 46: Subtask merge_all_trips
[2025-03-16T19:58:23.286+0000] {task_command.py:467} INFO - Running <TaskInstance: data_ingestion_bigquery_dag.merge_all_trips scheduled__2025-03-15T00:00:00+00:00 [running]> on host ea596c643a9a
[2025-03-16T19:58:24.438+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_ingestion_bigquery_dag' AIRFLOW_CTX_TASK_ID='merge_all_trips' AIRFLOW_CTX_EXECUTION_DATE='2025-03-15T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-15T00:00:00+00:00'
[2025-03-16T19:58:24.449+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-16T19:58:24.455+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-16T19:58:24.470+0000] {logging_mixin.py:190} INFO - Current task name:merge_all_trips state:running start_date:2025-03-16 19:58:22.093229+00:00
[2025-03-16T19:58:24.472+0000] {logging_mixin.py:190} INFO - Dag name:data_ingestion_bigquery_dag and current dag run status:running
[2025-03-16T19:58:24.474+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-16T19:58:37.260+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/data_ingestion_gcs.py", line 83, in merge_all_trips
    merged_table = pa.concat_tables(tables).combine_chunks()
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "pyarrow/table.pxi", line 6256, in pyarrow.lib.concat_tables
  File "pyarrow/error.pxi", line 155, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 92, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: Schema at index 1 was different: 
trip_id: int64
duration: int64
start_time: string
end_time: string
start_station: int64
start_lat: double
start_lon: double
end_station: int64
end_lat: double
end_lon: double
bike_id: string
plan_duration: int64
trip_route_category: string
passholder_type: string
bike_type: string
vs
trip_id: int64
duration: int64
start_time: string
end_time: string
start_station: int64
start_lat: double
start_lon: double
end_station: int64
end_lat: double
end_lon: double
bike_id: string
plan_duration: int64
trip_route_category: string
passholder_type: string
bike_type: string
year: int64
quarter: string
[2025-03-16T19:58:37.525+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-03-16T19:58:37.539+0000] {logging_mixin.py:190} INFO - Task start:2025-03-16 19:58:22.093229+00:00 end:2025-03-16 19:58:37.523989+00:00 duration:15.43076
[2025-03-16T19:58:37.541+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): merge_all_trips> dag:<DAG: data_ingestion_bigquery_dag> dagrun:<DagRun data_ingestion_bigquery_dag @ 2025-03-15 00:00:00+00:00: scheduled__2025-03-15T00:00:00+00:00, state:running, queued_at: 2025-03-16 19:52:34.678362+00:00. externally triggered: False>
[2025-03-16T19:58:37.542+0000] {logging_mixin.py:190} INFO - Failure caused by Schema at index 1 was different: 
trip_id: int64
duration: int64
start_time: string
end_time: string
start_station: int64
start_lat: double
start_lon: double
end_station: int64
end_lat: double
end_lon: double
bike_id: string
plan_duration: int64
trip_route_category: string
passholder_type: string
bike_type: string
vs
trip_id: int64
duration: int64
start_time: string
end_time: string
start_station: int64
start_lat: double
start_lon: double
end_station: int64
end_lat: double
end_lon: double
bike_id: string
plan_duration: int64
trip_route_category: string
passholder_type: string
bike_type: string
year: int64
quarter: string
[2025-03-16T19:58:37.570+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=data_ingestion_bigquery_dag, task_id=merge_all_trips, run_id=scheduled__2025-03-15T00:00:00+00:00, execution_date=20250315T000000, start_date=20250316T195822, end_date=20250316T195837
[2025-03-16T19:58:37.814+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-16T19:58:37.819+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 46 for task merge_all_trips (Schema at index 1 was different: 
trip_id: int64
duration: int64
start_time: string
end_time: string
start_station: int64
start_lat: double
start_lon: double
end_station: int64
end_lat: double
end_lon: double
bike_id: string
plan_duration: int64
trip_route_category: string
passholder_type: string
bike_type: string
vs
trip_id: int64
duration: int64
start_time: string
end_time: string
start_station: int64
start_lat: double
start_lon: double
end_station: int64
end_lat: double
end_lon: double
bike_id: string
plan_duration: int64
trip_route_category: string
passholder_type: string
bike_type: string
year: int64
quarter: string; 1256)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/data_ingestion_gcs.py", line 83, in merge_all_trips
    merged_table = pa.concat_tables(tables).combine_chunks()
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "pyarrow/table.pxi", line 6256, in pyarrow.lib.concat_tables
  File "pyarrow/error.pxi", line 155, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 92, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: Schema at index 1 was different: 
trip_id: int64
duration: int64
start_time: string
end_time: string
start_station: int64
start_lat: double
start_lon: double
end_station: int64
end_lat: double
end_lon: double
bike_id: string
plan_duration: int64
trip_route_category: string
passholder_type: string
bike_type: string
vs
trip_id: int64
duration: int64
start_time: string
end_time: string
start_station: int64
start_lat: double
start_lon: double
end_station: int64
end_lat: double
end_lon: double
bike_id: string
plan_duration: int64
trip_route_category: string
passholder_type: string
bike_type: string
year: int64
quarter: string
[2025-03-16T19:58:38.082+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-16T19:58:38.218+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-16T19:58:38.233+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
